---
title: "Households and Nonprofit Organizations"
author: "Tejas Prakash"
date: "Saturday, May 20, 2017"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r,warnings=FALSE,messages=FALSE}
library(ggplot2)
library(dplyr)
library(Hmisc)
series<-read.csv("csv/b101.csv")
descp<-read.delim("data_dictionary/b101.txt",col.names=c("Variable","Category","Line","Table","Amount"))
my_theme <-  theme_bw() + # White background, black and white theme
  theme(axis.text = element_text(size = 8, color = "indianred4"),
        text = element_text(size = 10, face = "bold", color = "darkslategrey"))
```

***
***

```{r,warnings=FALSE,messages=FALSE}
makeGraph <- function(v) {
 S<-filter(descp,Variable==v)
 category<-as.character(S$Category)
 category<-as.character((strsplit(category,";"))[[1]])
 category<-category[2:length(category)]
 category<-capitalize(trimws(category))
 title<-paste(c(category)," over Time",collapse="")
 units<-as.character(S$Amount)
 ylab<-paste(c(category," (",units,")"),collapse="")
 d<-series[v]
 ggplot(series,aes(x=as.vector(date),y=as.numeric(as.vector(d[,1]))))+geom_line(color="red",aes(group=1))+geom_point(color="blue")+scale_x_discrete(name="Year,Quarter",breaks=c("1945:Q4","1963:Q1","1981:Q1","1998:Q4","2016:Q4"))+labs(title=title,subtitle=units,y=category)+my_theme
}
```


***
***

#Variable FL153090005.Q

**Time Series for Total Miscellaneous Assets**
```{r}
makeGraph("FL153090005.Q")
```


***
***

#Variable LM155035005.Q

**Time Series for Real Estate at Market Value**

```{r}
makeGraph("LM155035005.Q")
```

***
***

#Variable FL154090005.Q

**Time Series for Total Financial Assets**

```{r}
makeGraph("FL154090005.Q")
```


***
***

#Variable FA156012005.Q

**Time Series for Disposable Personal Income**

```{r}
makeGraph("FA156012005.Q")
```


***
***